# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\"\x0e\n\x0cmessageInput\"\x1c\n\rmessageOutput\x12\x0b\n\x03msg\x18\x01 \x01(\t26\n\x04\x44\x65mo\x12.\n\x0bSendMessage\x12\r.messageInput\x1a\x0e.messageOutput\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEINPUT._serialized_start=14
  _MESSAGEINPUT._serialized_end=28
  _MESSAGEOUTPUT._serialized_start=30
  _MESSAGEOUTPUT._serialized_end=58
  _DEMO._serialized_start=60
  _DEMO._serialized_end=114
# @@protoc_insertion_point(module_scope)
